---
version: 2.1

orbs:
  terraform: twdps/terraform@0.6.0
  op: twdps/onepassword@1.0.0

# ==== global pipeline parameters

parameters:
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.3.3"
  context:
    description: circleci context for all jobs
    type: string
    default: cohorts-global
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file=op.env -- /bin/bash

# git push: run terraform plan
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release - terraform apply
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      acct:
        type: string
        default: ''
    steps:
      - op/env:
          env-file: op.env
      - run:
          name: set ~/.terraformrc
          command: op inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.acct >> environment variables
          command: op inject -i environments/<< parameters.acct >>.auto.tfvars.json.tpl -o << parameters.acct >>.auto.tfvars.json

workflows:
  version: 2

  hosted-zones change plan:
    jobs:
      - terraform/plan:
          name: hosted-zones change plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: state
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                acct: multiaccount
          filters: *on-push-main


  hosted-zones release:
    jobs:
      - terraform/apply:
          name: hosted-zones release
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: state
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                acct: multiaccount
          after-terraform:
            - run:
                name: test hosted zones 
                command: |
                  bash scripts/hosted_zone_test.sh multiaccount nonprod
          filters: *on-tag-main

  # generate-release-notes:
  #   jobs:
  #     - executor-tools/release:
  #         name: release-lab-platform-hosted-zones
  #         context: << pipeline.parameters.context >>
  #         shell: << pipeline.parameters.shell-options >>
  #         on-tag: true
  #         filters: *on-tag-main
